[package]
name = "palantir"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
color-eyre = "0.5"
warp = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
ctrlc = { version = "3", features = ["termination"] }
dotenv = "0.15"
regex = { version = "1", default-features = false, features = ["std"] }
once_cell = "1"
hostname = "0.3"
libc = "0.2"

[dev-dependencies]
iai = "0.1"

[[bench]]
name = "iai"
harness = false